packages:
  - ./
  - ./skills/srv-jsx/assets/vite-example
allowBuilds:
  esbuild: false
  sharp: false
  workerd: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: latest
overrides:
  srv-jsx: "workspace:"
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
